name: "Sync docs"
description: "Sync the documentation sites after the release"

runs:
  using: composite
  steps:
    - name: Fetch latest from origin
      run: git fetch origin
      shell: bash

    - name: Sync docs
      run: |
        pnpm gen:docs
        pnpm www:theme
        pnpm www:props
        pnpm www:changelog
        pnpm www:styled-system
        pnpm www:contributors
        pnpm www:search
        pnpm www:icon-tags
      shell: bash

    - name: Create PR
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ env.GITHUB_TOKEN }}
        base: v1
        commit-message: "ci(changesets): sync documentation"
        title: "Sync documentation"
        branch: v1/www
        assignees: "hirotomoyamada"
        reviewers: "hirotomoyamada"
